spring:
  application:
    name: consumer

server:
  port: 8081
  servlet:
    context-path: /consumer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

feign:
  hystrix:
    enabled: true
